services:
  - gulp
  - docker
language: node_js
node_js:
  node
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - gulp
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
after_success:
  - echo "$DOCKER_EMAIL $DOCKER_USER $DOCKER_PASS $DOCKER_PROJECT $TAG"
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $DOCKER_USER/$DOCKER_PROJECT:$COMMIT .
  - docker tag $DOCKER_USER/$DOCKER_PROJECT:$COMMIT $DOCKER_USER/$DOCKER_PROJECT:$TAG
  - docker tag $DOCKER_USER/$DOCKER_PROJECT:$COMMIT $DOCKER_USER/$DOCKER_PROJECT:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/$DOCKER_PROJECT
